name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-17"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMGZlM2EzNzUtNjhkOC00MTMzLWEwZjctNmRlNjFhZTk3Y2MzIiwidGVuYW50X2lkIjoiOGNiY2Y0MmU4NTg3MWM1YjQ1ZDcxYmVhOGI5NjFjYzQ5NGUxY2FmY2I0ZTcxNGUzODhjZWYzMTJhMmZjMDk0MyIsImludGVybmFsX3NlY3JldCI6IjczMzRmZDAyLTVlYTItNDllNC1iOWZhLWMzYjI1NmUxYWMzMCJ9.VXSwz9a5OzxLsROlc3EXAflEVLbnW0oM-HvaEoS_8tI"
JWT_SECRET = "abcd"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1